Try the following changes:

1.) In qtforms/loginbase[.ui/.py] remove the connection from the OK
button to the accept slot.

2.) Change the class Login in login.py

class Login(LoginBase):
    def __init__(self, poswindow):
        LoginBase.__init__(self)
-       self.authenticated = False
        self.poswindow = poswindow

    def authenticate(self):
        username=str(self.lnedUsername.text())
        password=str(self.lnedPassword.text())
        user=User.getUser(username, password)
        if user:
            self.poswindow.show()
-           self.authenticated = True
+           self.accept()
        else:
            self.authenticated = False
            QMessageBox.warning(None,
                self.trUtf8("Login Incorrect"),
                self.trUtf8("""The user id and password you entered is
incorrect."""),
                None,
                None,
                None,
                0, -1)
+           # If the authentication fails, the whole application ends as
requested.
+           # Do this only, if the user shouldn't get a second chance.
+           # Normally, the user should be able to try it again.
+           self.reject()
-       return self.authenticated
          

3.) Change the login method in the class QualityPos in qualitypos.py

class QualityPOS(QualityPOSBase):
    def login(self):
        loginwindow = Login(self)
        loginwindow.show()
-       loginwindow.exec_loop()
+       return loginwindow.exec_loop()


4.) Change main.py:

    qapp = QApplication(sys.argv)
    QObject.connect(qapp,SIGNAL("lastWindowClosed()"),qapp,SLOT("quit()"))
    poswindow = QualityPOS()
    qapp.setMainWidget(poswindow)
-   qapp.exec_loop()
+   if poswindow.login() == QDialog.Accepted:
+       qapp.exec_loop()


